### PR TITLE
Add Numerals Duo Synth Neon Green watchface.

### PR DESCRIPTION
**Pull request by MagneFire**
A different take on the neon watchface https://github.com/AsteroidOS/unofficial-watchfaces/pull/32
All credit for this one goes to @eLtMosen.

If you have a better name then that's also welcome :wink:

### CODE REVIEW

**Comment by eLtMosen** [comment]
Nope, the name is perfect :D
Reminds me to the "Finaldraft005-correction021-releaseready007.psd" nomenclature most designers end up in their projects.

**Comment by jrtberlin** [comment]
You could name it "Synth Neon Numerals". But if you both think it's good to go we should get that merged.

**Comment by eLtMosen** [comment]
> You could name it "Synth Neon Numerals". But if you both think it's good to go we should get that merged.

Really, whatever you like.

**Comment by MagneFire** [comment]
After a very extensive discussion we eventually came back to "Synth Neon Numerals" :laughing:

**Comment by MagneFire** [comment]
@eLtMosen Thanks for this watchface! I've been using it for a few days now, super awesome!

**Comment by FlorentRevest** [comment]
This is one heck of a sexy watchface! :D

**Pull request merged**
