### PR TITLE
Add animated Mickey Mouse watchface.

### PR DESCRIPTION
**Pull request by MagneFire**
This adds an animated Mickey Mouse watchface that was originally inspired by the Apple Watch :smile:

### CODE REVIEW

**Comment by MagneFire** [comment]
Unsure about how this watchface would work legally. To avoid issues this will not be merged.

**Comment by eLtMosen** [comment]
Agreed. Even though Disneys copyright for Mickey will partly end in 2024. This yields true only for the original incarnations and the one pictured is definitely a 70s version with Disney hodling all rights for long time to come...

**Comment by jrtberlin** [comment]
@eLtMosen isn't the copyright expiration US specific?

**Comment by eLtMosen** [comment]
Even without having any legal details, colliding with Disney is known to be a legal minefield. 
And the other way around, why should we even feature such a company the slightest by dedicating a homage to them. :P

BTW, for the Silly Walks design i am highly certain it is public domain. There are countless silly walks clock designs only that are marked public domain, just picking one obvious being Prusa who most definitely looked into licensing before claiming their design to be PD on their website. And since i drew our silly walks design from scratch, i am certain it 100% passes off as homage.
[Prusa Silly Walks design](https://www.prusaprinters.org/prints/68569-ministry-of-silly-walks-clock)

**Pull request closed without merging**
