### PR TITLE
Fix and optimize analog-scientific-v2

### PR DESCRIPTION
**Pull request by eLtMosen**
- Move canvases to cooperative renderingStrategy to solve the performance issues
- Optimize svg antialising using the layer samples method we found for QtShapes
- Supply and employ black and white only hands during AoD
- Heavily refactor syntax for better readability.

### CODE REVIEW

**Review by beroset — APPROVED** [review]
I find the omission of the leading 0 for numbers like `0.488` => `.488` a wee bit less readable, but it's a minor complaint and it's consistent within the watchface.  Saves a few bytes, as well, I suppose.  Consolidation and consistent ordering of `anchor`, `font`, etc. is excellent and greatly improves readability.

**Comment by eLtMosen** [comment]
> I find the omission of the leading 0 for numbers like `0.488` => `.488` a wee bit less readable, but it's a minor complaint and it's consistent within the watchface. 

Ha, i always found the 0 omission to be kind of smart when i first saw someone else doing it. Maybe for you its a bit less readable because of being used to the leading 0? Anyway, good point, have not thought about that. I was figuring the opposite actually since it shortens code lines by some chars eventually. And reading from left to right should be a tad faster?
I was planning to do the 0 omission consistently from now on, thinking its super leet. And now you,  the type of guy i seek to impress with such nifty things, points out a problem. I am devastated :joy_cat: Ahhh, trade-offs everywhere.

**Comment by beroset** [comment]
I wouldn't worry too much about it.  It's a minor difference, and I'm sure I can live with it either way.

**Review by FlorentRevest — APPROVED** [review]

**Comment by FlorentRevest** [comment]
Cool :) like beroset, I think the leading 0 is slightly more readable and I don't think we should optimize for code length but rather for readability. That being said it's really minor and we can absolutely deal with it ahah

**Comment by FlorentRevest** [comment]
Oh and thanks for the review beroset! This helps a lot when other folks review PRs, much appreciated.

**Pull request merged**
