### PR TITLE
Add analog-lenok watchface

### PR DESCRIPTION
**Pull request by CosmosDev**
Hi!

I added a watchface _heavily_ inspired by the LG G Watch R's default watchface.

Thank you to all the maintainers and contributors of this project!

### CODE REVIEW

**Comment by eLtMosen** [comment]
Great work, looks gorgeous!
Thank you very much for sharing.
I especially like how you combined svgs and repeaters for the complex "background".
Michroma is a cool addition to the font pool, much appreciated. 

Minor notes,
The SVGs contain all the inkscape meta data and redundant parts. They can be optimized with a tool like [svgo](https://github.com/svg/svgo) up to 1/5th of the current size.
Don't make the error and fall for those websites that offer to shrink one svg after another to keep you looking at their adds like i did in the beginning /o\

The thumbnails are swapped imo. The list suggests left column for colourful background image on a round watch. I take this a as opportunity to showcase the watchface/background combination i find most fitting.
Right column is ment to easily compare watchfaces on stock flat-mesh background and evaluate it on a square watch. 
Admitted, in the list that round vs square logic is broken also on my latest three watchfaces since i do not own a square watch anymore. I am working on a [watchface creation script](https://github.com/eLtMosen/unofficial-watchfaces/blob/master/test-in-qmlscene.sh) that displays the watchface in qmlscene so square screenshots can be taken hardware independent.
If you could swap your current thumbnails, i offer to add a proper square screenshot later on when i am in process to fix that issue with my latest contributions.

Thanks again. So great to see more contributions.
Yours is easily in my TOP 5 now!

**Comment by eLtMosen** [comment]
Haha, now i got an actual issue i can not solve.
I can not get the svgs to display on my bass. The svgs in subfolder analog-lenok/ work in qmlscene but when i use the ./deploy.sh to push it to bass, the svgs fail to load.
Might it be related to the folder having permission drwx------ when created by the deploy script?
I changed it to chmod 0644 but still they do not load?
How did you create the folder on the watch?
I am stuck and happy for every hint.

**Comment by FlorentRevest** [comment]
Great job @CosmosDev ! Thanks a lot :D

Let's give this a different name. Even though it looks a bit like the default WearOS watchface on lenok, this is an original artwork and we want to avoid any copyright confusion :) 

Once @eLtMosen's comments and the name are addressed, this is ready to merge :)

**Comment by CosmosDev** [comment]
Thank you for your comments @eLtMosen! And thank you for all of your contributions, which I used as a template to create this watchface.

I totally forgot about SVG optimization. I updated the repo with a new set of SVGs, and swapped the two thumbnails.

I do not own a square watch either, so I would gladly accept the offer of a square screenshot.

Thanks again!

**Comment by CosmosDev** [comment]
Thank you very much @FlorentRevest! 

I changed the name to analog-modern-steel. I am not the best at finding names, so if you have a better suggestion, I would be happy to hear it.

Please tell me if you need me to rename the PR as well.

Thanks!

**Comment by jrtberlin** [comment]
What's the state of this PR?

**Comment by FlorentRevest** [comment]
Oopsie :) the state was "forgotten" this looks good to merge. I will squash commits into one and rename the title. Thanks a lot!

**Pull request merged**
