### PR TITLE
Added deploy_adb.sh which deploys to a watch in ADB mode

### PR DESCRIPTION
**Pull request by basnappl**
I was having issues with ssh connectivity but adb worked.  So, I figured I'd just add the slightly modified script in case it might save someone else some time.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Hey @basnappl ! Sorry for the late review, I've been quite busy :) 
Sure adding an adb option could be nice. But what would you think of having it as a flag in the existing ./deploy.sh script ? This would make it easier to maintain one script instead of two

**Comment by basnappl** [comment]
Sounds like a good idea to me!

**Comment by eLtMosen** [comment]
Like so?
https://github.com/AsteroidOS/unofficial-watchfaces/pull/22/commits/75e4f1326e68d5cc4b71f017768dcb85b43c06fe

**Comment by FlorentRevest** [comment]
Yes, like this eLtMosen :) Thanks! I'm closing this PR then.

**Pull request closed without merging**
