### PR TITLE
Streamline analog-words and fix color issues

### PR DESCRIPTION
**Pull request by beroset**
Now the thumbnail is watchface selection and the main watch face both
correctly display color.

Signed-off-by: Ed Beroset <beroset@ieee.org>

### CODE REVIEW

**Comment by eLtMosen** [comment]
Awesome!
The code refactoring really blows me away. Much more elegant in many parts then before additionally to solving the "Watchface selection" thumbnail problem. 
As you mentioned on matrix there are minor changes to the visual appearance.
Most notably the currentHour had a bigger size which i would like to try to redesign since the purpose was to help with legibility.
The other change i spot is the overall size being slightly smaller then before.
My intention was to fully use the screen estate and make the thinner letters better readable on low resolution watches.
Did you change the overall size on purpose? Else i would like to try my luck and recreate the "original" appearance as pictured in the screenshot below.
Bildschirmfoto vom 2021-11-01 19-18-38

**Comment by beroset** [comment]
No, I didn't change the overall size on purpose.  I tried to match it as well as I could visually, but I see in the side-by-side pictures that I didn't get it quite right.  My computer doesn't have these fonts installed so it's a little hard to tell without downloading to the watch.  Looks like making the font a wee bit larger might take care of it.  I changed the font size multiplier on line 66 from 0.5 to 0.6 and on line 165 from 0.6 to 0.7.  It looks closer to me, but I'd appreciate if you adjust it to your preference for incorporation into the patch.

**Comment by beroset** [comment]
Try replacing line 110 with this and see what you think:
```
font.pixelSize: parent.height * (hour == index ? 0.75 : 0.7)

**Comment by eLtMosen** [comment]
That's not exactly it. With 0.75 the font is larger then in the OG and breaks in the SK translation with the 12 hour word dvanajst. 
The real difference is in spacing and font offset. It is hard to fully explain for me as a non pro designer but from the few principles i learned:
In the OG the spacings where all equally 18px around the fonts. Which made the leaf boxes slightly longer then in the refactored version. The font size is quite the same in both versions but the OffSet is missing which now centers the font to the taler letters (f,h,t etc) and not to the more frequent shorter letters (a, c, e, m, etc).
For floating text this is the norm since in sentences, the taler letters dominate, especially with uppercase use. In this lower case design piece however every word stands for itself in lowercase and thus the centering and equal spacing needs to be done to the more frequent shorter letters, with the few taler letters slightly moving off center.
Since i can't better explain i'd like to try pick on from here and trial and error my way through. That might take a little longer then your ninja answers :D
Just to illustrate the spacing:

Bildschirmfoto vom 2021-11-01 19-18-38

**Comment by eLtMosen** [comment]
I give up trying to commit to your branch /o\
Can't get by some "Fast Forward" error i do not understand since an hour and decided to just wrap it up in a zip...
The needed changes where indeed minor and i took the opportunity to test the layout against all translations again and made changes to the currentHour letterspacing so the longer words do display better.
Played with drop shadows and was quite satisfied with the result. The colors now look much better separated and with some contrast.
Sorry again for not following Github etiquette. I simply failed to understand anything above committing from my master branch as of yet...

[analog-words.zip](https://github.com/AsteroidOS/unofficial-watchfaces/files/7456738/analog-words.zip)
words11

**Comment by beroset** [comment]
Nice!  I'll try it out and revise my commit.

**Comment by beroset** [comment]
Good fixes -- it's much improved!  I tried adding Russian but as not entirely unexpected, it doesn't quite fit on the screen because the words for 11 and 12 are relatively long (одиннадцать, двенадцать) so I think it's good enough to commit as is (without Russian for now) if you agree.

**Comment by eLtMosen** [comment]
Absolutely! And thanks again.
I tried all languages AOS has in stock but only the ones that ended up in the final where consistently "short enough" for the design.

**Comment by FlorentRevest** [comment]
Cool stuff! I really like this watchface, especially with the drop shadows :)

**Pull request merged**
