### PR TITLE
added analog-classy-roman watchface

### PR DESCRIPTION
**Pull request by eLtMosen**
Trying to contribute to 2.0 with some more straight forward, legibility optimized designs with AOS logo integrated.
Please review this in light to possibly become a stock watchface.
Any suggestion to streamline it further and hit a broad taste are very welcome.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
It'd already be a great addition to the unofficial watchfaces collection :D 

I currently don't see it fit in the default set though. I struggle really hard to explain exactly why and that bothers me a bit. I feel like I have the duty to evaluate things as objectively as possible but because I don't have in depth design knowledge I don't feel comfortable reviewing a design like I would review a code ahah.

Anyway, if I were to try to explain my idea of the official set (it would actually be beneficial to have a set of rules written down somewhere to help with this in the future), I see them as pretty "low profile", standard minimalistic instances of a watchface style. A lot of things make this watchface feel heavy, like the logo on top, all the text behind, the colors of the handles, it's also what gives it a bit of a classical feeling but it makes me wonder whether it makes sense to have a classical style watchface in the default set of a smart watch os.

Ugh, I wish my review could be more helpful! :D Maybe other members have opinions on matrix ?

**Comment by eLtMosen** [comment]
>but it makes me wonder whether it makes sense to have a classical style watchface in the default set of a smart watch os.

Agreed.
Though we have classic watchfaces in stock, this attempt might very well be overdone and too heavy.
And don't lower yourself. We have admitted and established that we are not designers. Still reviewers did like what we came up with out past trial and error, so we have that going for us :D Thus, arguing the way you did is what i was looking for to narrow down on a direction.
I do not mind to do more attempts and just fill the unofficial repo with more options.
And to everyone, just do not hold back comments and suggestions please. Everything is helpful and there is no way to offend me.

**Comment by eLtMosen** [comment]
I guess it is good to go for unofficial section then.
Will try to come up with more simpler attempts for 2.0.

**Comment by FlorentRevest** [comment]
Thank you @eLtMosen !

**Pull request merged**
