### PR TITLE
Update qml syntax

### PR DESCRIPTION
**Pull request by beroset**
This fixes all warnings of the type "QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }" and fixed error in `sporty-round` with references to undefined `secondArc`.

### CODE REVIEW

**Comment by beroset** [comment]
Hmmm.  The first three commits seem to be residue from an issue that has already been merged, but I believe the overall result is correct anyway.

**Comment by eLtMosen** [comment]
Great, it always bugged me that those errors where thrown. Much much appreciated!
Can't say how happy i am to learn from your work.
"The first three commits" in your case, many more already merged commits sometimes showing up again in later PRs is an issue i often have and would love to even understand why that happens.
The only way i found to avoid that is starting off with a fresh fork... whenever i commit multiple PRs from the same fork, some already merged commits show up again.

**Comment by beroset** [comment]
I think I've figured out how I messed this up.  I created a branch without a `pull` from the upstream master which meant that it did not include the commits that had *already* been merged there.  I have also found some other problems with this commit, so will mark it as draft until they are sorted out.  See [this](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork) for how to set the upstream URL if you didn't already know.

**Comment by FlorentRevest** [comment]
Thanks for this change! :) I took the freedom to solve the merge conflict manually.

Similarly to my comment here https://github.com/AsteroidOS/libasteroid/pull/7#issuecomment-968332063 I'd recommend using interactive rebases to keep the log clean. In this case again it's simple enough that I can squash everything into one.

**Pull request merged**
